#!/bin/sh

git submodule init
git submodule update
mkdir -p cbuild
cd cbuild

if [ "$1" == emscripten ]; then
   if [ -z "$EMSCRIPTEN_ROOT_PATH" ]; then
      echo "Please set the environment variable \$EMSCRIPTEN_ROOT_PATH"
      echo "to the location of the emscripten sdk."
      exit 1
   fi
   export C_FLAGS="${C_FLAGS} -Wno-warn-absolute-paths --preload-file ../work"
   cmake "${@:2}:" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=${EMSCRIPTEN_ROOT_PATH}/cmake/Modules/Platform/Emscripten.cmake ../
else
   cmake "$@" ../
fi

make -j10 install

