
Import('environment')

misc = ['SConscript']

srcs = [
  'cAnalyze.cc',
  'cAnalyzeGenotype.cc',
  'cAnalyzeUtil.cc',
  'cAnalyzeJobQueue.cc',
  'cAnalyzeJobWorker.cc',
  'cMutationalNeighborhood.cc'
]

hdrs = [
  'cAnalyze.h',
  'cAnalyzeCommand.h',
  'cAnalyzeCommandAction.h',
  'cAnalyzeCommandDef.h',
  'cAnalyzeCommandDefBase.h',
  'cAnalyzeFlowCommand.h',
  'cAnalyzeFlowCommandDef.h',
  'cAnalyzeFunction.h',
  'cAnalyzeGenotype.h',
  'cAnalyzeJob.h',
  'cAnalyzeJobQueue.h',
  'cAnalyzeJobWorker.h',
  'cAnalyzeUtil.h',
  'cGenotypeBatch.h',
  'cMutationalNeighborhood.h',
  'cMutationalNeighborhoodResults.h',
  'tAnalyzeJob.h',
]

environment.Library('analyze', srcs) 

environment.AppendUnique(
  avida_msvs_project_srcs = [File(src).srcnode().path for src in srcs],
  avida_msvs_project_incs = [File(src).srcnode().path for src in hdrs],
  avida_msvs_project_misc = [File(src).srcnode().path for src in misc],
)

# vim: set ft=python:
