
Import('environment')

misc = ['SConscript']

incs = [
  'cCodeLabel.h',
  'cCPUMemory.h',
  'cCPUStack.h',
  'cCPUTestInfo.h',
  'cHardwareBase.h',
  'cHardwareCPU.h',
  'cHardwareExperimental.h',
  'cHardwareGX.h',
  'cHardwareManager.h',
  'cHardwareSMT.h',
  'cHardwareStatusPrinter.h',
  'cHardwareTracer.h',
  'cHardwareTrans.h',
  'cHeadCPU.h',
  'cInstLib.h',
  'cInstSet.h',
  'cTestCPU.h',
  'cTestCPUInterface.h',
  'nHardware.h',
  'sCPUStats.h',
  'tInstLib.h',
]

srcs = [
  'cCodeLabel.cc',
  'cCPUMemory.cc',
  'cCPUStack.cc',
  'cCPUTestInfo.cc',
  'cHardwareBase.cc',
  'cHardwareCPU.cc',
  'cHardwareExperimental.cc',
  'cHardwareGX.cc',
  'cHardwareManager.cc',
  'cHardwareSMT.cc',
  'cHardwareStatusPrinter.cc',
  'cHardwareTransSMT.cc',
  'cHeadCPU.cc',
  'cInstSet.cc',
  'cTestCPU.cc',
  'cTestCPUInterface.cc',
]

environment.Library('cpu', srcs) 

environment.AppendUnique(
  avida_msvs_project_srcs = [File(src).srcnode().path for src in srcs],
  avida_msvs_project_incs = [File(src).srcnode().path for src in incs],
  avida_msvs_project_misc = [File(src).srcnode().path for src in misc],
)
  
# vim: set ft=python:
