
Import('environment')

environment.Library('cpu',
  [
    'cCodeLabel.cc',
    'cCPUMemory.cc',
    'cCPUStack.cc',
    'cCPUTestInfo.cc',
    'cHardware4Stack.cc',
    'cHardware4Stack_Thread.cc',
    'cHardwareBase.cc',
    'cHardwareCPU.cc',
    'cHardwareCPU_Thread.cc',
    'cHardwareManager.cc',
    'cHardwareSMT.cc',
    'cHardwareSMT_Thread.cc',
    'cHardwareStatusPrinter.cc',
    'cHeadCPU.cc',
    'cHeadMultiMem.cc',
    'cTestCPU.cc',
    'cTestCPUInterface.cc',
    'cTestUtil.cc',
  ],
) 
  
# vim: set ft=python:
