
Import('environment')

misc = ['SConscript']

incs = [
  'cCodeLabel.h',
  'cCPUMemory.h',
  'cCPUStack.h',
  'cCPUTestInfo.h',
  'cHardwareBase.h',
  'cHardwareCPU.h',
  'cHardwareCPU_Thread.h',
  'cHardwareManager.h',
  'cHardwareSMT.h',
  'cHardwareStatusPrinter.h',
  'cHardwareTracer.h',
  'cHardwareTrans.h',
  'cHeadCPU.h',
  'cHeadMultiMem.h',
  'cInstLibCPU.h',
  'cTestCPU.h',
  'cTestCPUInterface.h',
  'cTestUtil.h',
  'nHardware.h',
  'nHardwareCPU.h',
  'sCPUStats.h',
  'tInstLib.h',
]

srcs = [
  'cCodeLabel.cc',
  'cCPUMemory.cc',
  'cCPUStack.cc',
  'cCPUTestInfo.cc',
  'cHardwareBase.cc',
  'cHardwareCPU.cc',
  'cHardwareCPU_Thread.cc',
  'cHardwareManager.cc',
  'cHardwareSMT.cc',
  'cHardwareStatusPrinter.cc',
  'cHardwareTransSMT.cc',
  'cHeadCPU.cc',
  'cHeadMultiMem.cc',
  'cTestCPU.cc',
  'cTestCPUInterface.cc',
  'cTestUtil.cc',
]

environment.Library('cpu', srcs) 

environment.AppendUnique(
  avida_msvs_project_srcs = [File(src).srcnode().path for src in srcs],
  avida_msvs_project_incs = [File(src).srcnode().path for src in incs],
  avida_msvs_project_misc = [File(src).srcnode().path for src in misc],
)
  
# vim: set ft=python:
