
Import('environment')

environment.Library('classification',
  [
    'cClassificationManager.cc',
    'cGenotype.cc',
    'cGenotype_BirthData.cc',
    'cGenotypeControl.cc',
    'cInjectGenotype.cc',
    'cInjectGenotypeControl.cc',
    'cInjectGenotypeQueue.cc',
    'cLineage.cc',
    'cSpecies.cc',
    'cSpeciesControl.cc',
    'cSpeciesQueue.cc',
  ],
) 


# vim: set ft=python:
