import os.path
import string
import tempfile


def Test(env, name, *args, **kw):
  """Creates unit test.

  env: an SCons environment.
  remaining parameters: are passed directly to SCons 'Program' builder,
  and typically include first a program name, then a list of source
  files, and then optional arguments such as library specifications.

  Makes two alii: 'test-' plus the name of the test program, and
  'test-all':
  - first can be used to run individual unit test.
  - second runs all test programs.
  """
  prg = env.Program(name, *args, **kw)
  name = 'test-' + str(prg[0])
  path = prg[0].path
  env.AlwaysBuild(env.Alias(name, [prg], path))
  env.AlwaysBuild(env.Alias('test-all', [prg], path))

Import('environment')

all_libs = [
  'main',
  'classification',
  'cpu',
  'event',
  'analyze',
  'drivers',
  'analyze',
  'cpu',
  'tools',
  'actions',
  'main',
  #'archive',
  #'boost_serialization',
]

#Test(environment, 'full-unit-tests', 'full-unit-tests.cc', LIBS = all_libs)
#Test(environment, 'cInitFile-unit-tests', 'cInitFile-unit-tests.cc', LIBS = all_libs)

# vim: set ft=python:
