Import('environment')

environment.Install('$configPrefix', [
  'analyze.cfg',
  'environment.cfg',
  'events.cfg',
  'avida.cfg',
  'instset-classic.cfg',
  'instset-sex-classic.cfg',
  'instset-smt.cfg',
  'instset-transsmt.cfg',
  'default-classic.org',
  'default-sex-classic.org',
  'default-smt.org',
  'default-transsmt.org',
] )

# vim: set ft=python:
