import os
import os.path
import sys

Import('environment')

misc = ['SConscript']

srcs = ['primitive.cc']

libs = [
    'main',
    'classification',
    'cpu',
    'analyze',
    'drivers',
    'cpu',
    'tools',
    'actions',
    'analyze',
    #'archive',
    #'boost_serialization',
    'main',
  ]
if environment['PLATFORM'] not in ('win32'):
  libs = libs + ['pthread']
if environment['enableTCMalloc'] in ('True', '1', 1):
  libs = libs + ['tcmalloc']

avida_exe = environment.Program('avida',
  srcs,
  LIBS = libs,
)
environment.Install('$execPrefix', avida_exe)
# Make avida_exe visible to other SConscript files by the command
# "Import('avida_exe')"
environment.Export('avida_exe')

environment.AppendUnique(
  avida_msvs_project_srcs = [File(src).srcnode().path for src in srcs],
  avida_msvs_project_misc = [File(src).srcnode().path for src in misc],
)

# vim: set ft=python:
