Import('environment')

avida_LIBS = [
    'main',
    'classification',
    'cpu',
    'event',
    'analyze',
    'drivers',
    'analyze',
    'cpu',
    'tools',
    'actions',
    'ncurses',
    'pthread',
    'archive',
    'boost_serialization',
    'main',
  ]
if environment['enableTCMalloc'] in ('True', '1', 1):
  avida_LIBS = avida_LIBS + ['tcmalloc']

avida = environment.Program('avida',
  'primitive.cc',
  LIBS = avida_LIBS,
)
environment.Install('$execPrefix', avida)


# vim: set ft=python:
