Import('environment')

avida = environment.Program('avida',
  'primitive.cc',
  LIBS = [
    'main',
    'classification',
    'cpu',
    'event',
    'analyze',
    'drivers',
    'analyze',
    'cpu',
    'tools',
    'actions',
    'main',
    'archive',
    'boost_serialization',
  ],
)
environment.Install('$execPrefix', avida)


# vim: set ft=python:
