
Import('environment')

environment.Library('drivers',
  [
    'cDefaultAnalyzeDriver.cc',
    'cDefaultRunDriver.cc',
    'cDriverManager.cc',
    'cFallbackWorldDriver.cc',
  ],
) 

  
# vim: set ft=python:
