##############################################################################
## Copyright (C) 1999-2005 Michigan State University                        ##
## Based on work Copyright (C) 1993-2003 California Institute of Technology ##
##                                                                          ##
## Read the COPYING and README files, or contact 'avida@alife.org',         ##
## before continuing.  SOME RESTRICTIONS MAY APPLY TO USE OF THIS FILE.     ##
##############################################################################
    
import os
    
Import('environment')
e = environment

pf = e.File('pyste_util.py')
e.Local(pf)

package_name = 'AvidaCore'
package_modules = e.PystePackageSubmodule(
  [
    #  These classes must be loaded before its subclasses, so they must
    #  be listed early in this PystePackageSubmodule command.
    'cHelpEntry.pyste',
    'cSchedule.pyste',
    'cString.pyste',

    #  cBlockStruct is not used in Avida. @kgn
    #'cBlockStruct.pyste',

    'cChangeList.pyste',
    'cConstSchedule.pyste',
    'cCountTracker.pyste',

    #  No longer used. @kgn
    #'cCycleCheck.pyste',

    'cDataEntry.pyste',
    'cDataFile.pyste',
    'cDataFileManager.pyste',
    'cDataManager_Base.pyste',
    'cDefaultMessageDisplay.pyste',
    'cDoubleSum.pyste',
    'cFile.pyste',
    'cFixedBlock.pyste',
    'cFixedCoords.pyste',

    #  No longer used. @kgn
    #'cGenesis.pyste',

    'cHelpAlias.pyste',
    'cHelpFullEntry.pyste',
    'cHelpManager.pyste',
    'cHelpType.pyste',
    'cHistogram.pyste',

    #  No longer used. @kgn
    #'cID.pyste',

    'cIndexedBlockStruct.pyste',
    'cInitFile.pyste',
    'cIntSum.pyste',
    'cIntegratedSchedule.pyste',
    'cIntegratedScheduleNode.pyste',
    'cMerit.pyste',

    #  These rely on the third-party library "trio", which isn't
    #  incorporated yet... @kgn
    #'cMessageClass.pyste',
    #'cMessageClosure.pyste',
    #'cMessageDisplay.pyste',
    #'cMessageDisplay_headers.pyste',
    #'cMessageType.pyste',

    'cProbSchedule.pyste',
    'cRandom.pyste',
    'cRefBlock.pyste',
    'cRunningAverage.pyste',

    #  cScaledBlock is not used in Avida. @kgn
    #'cScaledBlock.pyste',

    'cStringIterator.pyste',
    'cStringList.pyste',
    'cStringUtil.pyste',
    'cThread.pyste',
    'cTools.pyste',
    'cUInt.pyste',
    #  No longer used. @kgn
    #'cUnitTestHelper.pyste',
    #'cVerifierSuiteRecurser.pyste',

    'cWeightedIndex.pyste',

    #  Wrappers not yet complete. @kgn
    #'functions.pyste',
    #'lightweight_test.pyste',
    #'nTemplateTests.pyste',
    #'tArgDataEntry.pyste',
    #'tArray.pyste',
    #'tBuffer.pyste',
    #'tDataEntry.pyste',
    #'tDataEntryBase.pyste',
    #'tDataEntryCommand.pyste',
    #'tDataManager.pyste',
    #'tDictionary.pyste',
    #'tHashTable.pyste',
    #'tList.pyste',
    #'tManagedPointerArray.pyste',
    #'tMatrix.pyste',
    #'tMemTrack.pyste',
    #'tObjectFactory.pyste',
    #'tSmartArray.pyste',
    #'tVector.pyste',
  ],
  pyste_package_name = package_name,
  LIBS = ['tools'],
)
package_init_file = e.PystePackageInitFile(
  package_modules,
  pyste_package_name = package_name,
)
package = e.PystePackage(
  package_modules + package_init_file,
  pyste_package_name = package_name,
)

package_install_dir = os.path.join(e['execPrefix'], package_name)
e.Install(
  package_install_dir,
  [package_modules, package_init_file]
)
e.Alias(
  'install',
  package_install_dir
)

#
# vim: set ft=python:
