
Import('environment')

misc = ['SConscript']

incs = [
  'cAction.h',
  'cActionLibrary.h',
  'DriverActions.h',
  'EnvironmentActions.h',
  'LandscapeActions.h',
  'PopulationActions.h',
  'PrintActions.h',
  'SaveLoadActions.h',
]

srcs = [
  'cActionLibrary.cc',
  'DriverActions.cc',
  'EnvironmentActions.cc',
  'LandscapeActions.cc',
  'PopulationActions.cc',
  'PrintActions.cc',
  'SaveLoadActions.cc',
]

tools_library = environment.Library('actions', srcs)

environment.AppendUnique(
  avida_msvs_project_srcs = [File(src).srcnode().path for src in srcs],
  avida_msvs_project_incs = [File(src).srcnode().path for src in incs],
  avida_msvs_project_misc = [File(src).srcnode().path for src in misc],
)

# vim: set ft=python:
