
Import('environment')

tools_library = environment.Library('actions',
  [
    'cActionLibrary.cc',
    'LandscapeActions.cc',
    'PrintActions.cc',
    'SaveLoadActions.cc',
  ],
)

# vim: set ft=python:
