
Import('environment')

environment.SConscript( [
  'actions/SConscript',
  'analyze/SConscript',
  'archive/SConscript',
  'classification/SConscript',
  'cpu/SConscript',
  'drivers/SConscript',
  'event/SConscript',
  'main/SConscript',
  'platform/SConscript',
  'targets/SConscript',
  'third-party/SConscript',
  'tools/SConscript',
  #'support/SConscript',
  #'utils/SConscript',
] )

if environment['enableTestCode'] in ('True', '1', 1):
  environment.SConscript('testsuites/SConscript')

# vim: set ft=python:
