
Import('environment')

environment.Library('cursesviewer',
  [
    'cAnalyzeScreen.cc',
    'cAnalyzeView.cc',
    'cBarScreen.cc',
    'cEnvironmentScreen.cc',
    'cHistScreen.cc',
    'cMapScreen.cc',
    'cMenuWindow.cc',
    'cOptionsScreen.cc',
    'cScreen.cc',
    'cStatsScreen.cc',
    'cSymbolUtil.cc',
    'cTextViewerAnalyzeDriver.cc',
    'cTextViewerDriver.cc',
    'cTextViewerDriver_Base.cc',
    'cTextWindow.cc',
    'cView.cc',
    'cViewInfo.cc',
    'cZoomScreen.cc',
  ],
) 

avida_viewer_LIBS = [
    'cursesviewer',
    'main',
    'classification',
    'cpu',
    'analyze',
    'drivers',
    'cpu',
    'tools',
    'actions',
    'analyze',
    'ncurses',
    'pthread',
    #'archive',
    #'boost_serialization',
    'main',
  ]
if environment['enableTCMalloc'] in ('True', '1', 1):
  avida_viewer_LIBS = avida_viewer_LIBS + ['tcmalloc']

avida_viewer = environment.Program(
  'avida-viewer',
  'viewer.cc',
  LIBS = avida_viewer_LIBS,
  LIBPATH = environment['LIBPATH'] + ['.'],
)
environment.Install('$execPrefix', avida_viewer)

# vim: set ft=python:
